---
- name: Install package using variable
  hosts: webservers
  become: yes

  vars:
    package_name: git

  tasks:
    - name: Install package
      apt:
        name: "{{ package_name }}"
        state: present
